version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nest-app:
    build:
      context: ./back-innova/
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3001:3001'
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpassword
      DATABASE_NAME: nestdb
      JWT_SECRET: 'secreto'
      PORT: 3001
    depends_on:
      - postgres
volumes:
  postgres_data:
